### ISSUE TITLE
HEInstaller>>#asSlots: cannot process well empty instance variables

### ISSUE THREAD

**Issue by pavel-krivanek** [tesonep/hermes#1]
if the input of HEInstaller>>#asSlots: is an empty string as in case of most of the classes, it returns {#'' => InstanceVariableSlot}

See:
('' splitOn: ' ') collect: [ :e | e asSymbol asSlot ] as: Array "{#'' => InstanceVariableSlot}"

**Comment by tesonep** [comment]
I have fixed in the new version.

Cheers.
