### ISSUE TITLE
Hermes cannot process WideString literals

### ISSUE THREAD

**Issue by pavel-krivanek** [tesonep/hermes#14]
Hermes cannot process WideString literals. Required for the Collections-Tests package

**Comment by tesonep** [comment]
It should be fixed since v2.2.0, which version are you using? You should use v2.2.1 that is supposed to have an improvement in the export of code.

**Comment by pavel-krivanek** [comment]
the version used in bootstrap: 2.1.0
I'll check

**Comment by pavel-krivanek** [comment]
works, closing
